final Map<String, dynamic> aliasesRU = {
  'AUD': 'Австралийский доллар',
  'AZN': 'Азербайджанский манат',
  'ARS': 'Аргентинский песо',
  'AMD': 'Армянский драм',
  'BYN': 'Белорусский рубль',
  'BGN': 'Болгарский лев',
  'BRL': 'Бразильский реал',
  'GBP': 'Британский фунт стерлингов',
  'VND': 'Вьетнамский донг',
  'HKD': 'Гонконгский доллар',
  'GEL': 'Грузинский лари',
  'DKK': 'Датская крона',
  'AED': 'Дирхам ОАЭ',
  'USD': 'Доллар США',
  'EUR': 'Евро',
  'EGP': 'Египетский фунт',
  'ILS': 'Израильский шекель',
  'INR': 'Индийская рупия',
  'IDR': 'Индонезийская рупия',
  'IRR': 'Иранский риал',
  'ISK': 'Исландская крона',
  'KZT': 'Казахстанский тенге',
  'CAD': 'Канадский доллар',
  'KGS': 'Киргизский сом',
  'CNY': 'Китайский юань',
  'LVL': 'Латвийский лат',
  'LTL': 'Литовский лит',
  'MVR': 'Мальдивская руфия',
  'MXN': 'Мексиканский песо',
  'MDL': 'Молдавский лей',
  'MNT': 'Монгольский тугрик',
  'NPR': 'Непальская рупия',
  'NZD': 'Новозеландский доллар',
  'NOK': 'Норвежская крона',
  'PLN': 'Польский злотый',
  'RUB': 'Российский рубль',
  'RON': 'Румынский лей',
  'SCR': 'Сейшельская рупия',
  'RSD': 'Сербский динар',
  'SGD': 'Сингапурский доллар',
  'TJS': 'Таджикский сомони',
  'TWD': 'Тайваньский доллар',
  'THB': 'Тайский бат',
  'TRY': 'Турецкая лира',
  'TMT': 'Туркменский манат',
  'UZS': 'Узбекский сум',
  'UAH': 'Украинская гривна',
  'PHP': 'Филиппинский песо',
  'HRK': 'Хорватская куна',
  'CZK': 'Чешская крона',
  'CLP': 'Чилийский песо',
  'SEK': 'Шведская крона',
  'CHF': 'Швейцарский франк',
  'KRW': 'Южнокорейская вона',
  'JPY': 'Японская иена',
  'BTC': 'Биткоин',
  'XAU': 'Золото (тройская унция)',
  'XAG': 'Серебро (тройская унция)',
};

final Map<String, dynamic> aliasesEN = {
  'ARS': 'Argentine Peso',
  'AMD': 'Armenian Dram',
  'AUD': 'Australian Dollar',
  'AZN': 'Azerbaijani Manat',
  'BYN': 'Belarusian Ruble',
  'BRL': 'Brazilian Real',
  'GBP': 'British Pound Sterling',
  'BGN': 'Bulgarian Lev',
  'CAD': 'Canadian Dollar',
  'CLP': 'Chilean Peso',
  'CNY': 'Chinese Yuan',
  'HRK': 'Croatian Kuna',
  'CZK': 'Czech Koruna',
  'DKK': 'Danish Krone',
  'EGP': 'Egyptian Pound',
  'EUR': 'Euro',
  'GEL': 'Georgian Lari',
  'HKD': 'Hong Kong Dollar',
  'ISK': 'Icelandic Krona',
  'INR': 'Indian Rupee',
  'IDR': 'Indonesian Rupiah',
  'IRR': 'Iranian Rial',
  'ILS': 'Israeli Sheqel',
  'JPY': 'Japanese Yen',
  'KZT': 'Kazakhstani Tenge',
  'KGS': 'Kyrgystani Som',
  'LVL': 'Latvian Lats',
  'LTL': 'Lithuanian Litas',
  'MVR': 'Maldivian Rufiyaa',
  'MXN': 'Mexican Peso',
  'MDL': 'Moldovan Leu',
  'MNT': 'Mongolian Tugrik',
  'NPR': 'Nepalese Rupee',
  'NZD': 'New Zealand Dollar',
  'NOK': 'Norwegian Krone',
  'PHP': 'Philippine Peso',
  'PLN': 'Polish Zloty',
  'RON': 'Romanian Leu',
  'RUB': 'Russian Ruble',
  'RSD': 'Serbian Dinar',
  'SCR': 'Seychellois Rupee',
  'SGD': 'Singapore Dollar',
  'KRW': 'South Korean Won',
  'SEK': 'Swedish Krona',
  'CHF': 'Swiss Franc',
  'TWD': 'Taiwan Dollar',
  'TJS': 'Tajikistani Somoni',
  'THB': 'Thai Baht',
  'TRY': 'Turkish Lira',
  'TMT': 'Turkmenistani Manat',
  'UAH': 'Ukrainian Hryvnia',
  'AED': 'United Arab Emirates Dirham',
  'USD': 'United States Dollar',
  'UZS': 'Uzbekistan Som',
  'VND': 'Vietnamese Dong',
  'BTC': 'Bitcoin',
  'XAU': 'Gold (troy ounce)',
  'XAG': 'Silver (troy ounce)',
};

final List<String> currenciesOrderEN = [
  'ARS',
  'AMD',
  'AUD',
  'AZN',
  'BYN',
  'BRL',
  'GBP',
  'BGN',
  'CAD',
  'CLP',
  'CNY',
  'HRK',
  'CZK',
  'DKK',
  'EGP',
  'EUR',
  'GEL',
  'HKD',
  'ISK',
  'INR',
  'IDR',
  'IRR',
  'ILS',
  'JPY',
  'KZT',
  'KGS',
  'LVL',
  'LTL',
  'MVR',
  'MXN',
  'MDL',
  'MNT',
  'NPR',
  'NZD',
  'NOK',
  'PHP',
  'PLN',
  'RON',
  'RUB',
  'RSD',
  'SCR',
  'SGD',
  'KRW',
  'SEK',
  'CHF',
  'TWD',
  'TJS',
  'THB',
  'TRY',
  'TMT',
  'UAH',
  'AED',
  'USD',
  'UZS',
  'VND',
  'BTC',
  'XAU',
  'XAG'
];

final List<String> currenciesOrderRU = [
  'AUD',
  'AZN',
  'ARS',
  'AMD',
  'BYN',
  'BGN',
  'BRL',
  'GBP',
  'VND',
  'HKD',
  'GEL',
  'DKK',
  'AED',
  'USD',
  'EUR',
  'EGP',
  'ILS',
  'INR',
  'IDR',
  'IRR',
  'ISK',
  'KZT',
  'CAD',
  'KGS',
  'CNY',
  'LVL',
  'LTL',
  'MVR',
  'MXN',
  'MDL',
  'MNT',
  'NPR',
  'NZD',
  'NOK',
  'PLN',
  'RUB',
  'RON',
  'SCR',
  'RSD',
  'SGD',
  'TJS',
  'TWD',
  'THB',
  'TRY',
  'TMT',
  'UZS',
  'UAH',
  'PHP',
  'HRK',
  'CZK',
  'CLP',
  'SEK',
  'CHF',
  'KRW',
  'JPY',
  'BTC',
  'XAU',
  'XAG'
];
