final Map<String, dynamic> aliasesRU = {
  "RUB": "Российский рубль",
  "USD": "Доллар США",
  "EUR": "Евро",
  "BYN": "Белорусский рубль",
  "KZT": "Казахстанский тенге",
  "AMD": "Армянский драм",
  "ARS": "Аргентинский песо",
  "AUD": "Австралийский доллар",
  "AZN": "Азербайджанский манат",
  "BGN": "Болгарский лев",
  "BRL": "Бразильский реал",
  "CAD": "Канадский доллар",
  "CHF": "Швейцарский франк",
  "CLP": "Чилийский песо",
  "CNY": "Китайский юань",
  "CZK": "Чешская крона",
  "DKK": "Датская крона",
  "AED": "Дирхам ОАЭ",
  "EGP": "Египетский фунт",
  "GBP": "Британский фунт стерлингов",
  "GEL": "Грузинский лари",
  "HKD": "Гонконгский доллар",
  "HRK": "Хорватская куна",
  "IDR": "Индонезийская рупия",
  "ILS": "Израильский шекель",
  "INR": "Индийская рупия",
  "IRR": "Иранский риал",
  "ISK": "Исландская крона",
  "JPY": "Японская иена",
  "KGS": "Киргизский сом",
  "KRW": "Южнокорейская вона",
  "LTL": "Литовский лит",
  "LVL": "Латвийский лат",
  "MDL": "Молдавский лей",
  "MNT": "Монгольский тугрик",
  "MVR": "Мальдивская руфия",
  "MXN": "Мексиканский песо",
  "NOK": "Норвежская крона",
  "NPR": "Непальская рупия",
  "NZD": "Новозеландский доллар",
  "PHP": "Филиппинский песо",
  "PLN": "Польский злотый",
  "RON": "Румынский лей",
  "RSD": "Сербский динар",
  "SCR": "Сейшельская рупия",
  "SEK": "Шведская крона",
  "SGD": "Сингапурский доллар",
  "THB": "Тайский бат",
  "TJS": "Таджикский сомони",
  "TMT": "Туркменский манат",
  "TRY": "Турецкая лира",
  "TWD": "Тайваньский доллар",
  "UAH": "Украинская гривна",
  "UZS": "Узбекский сум",
  "VND": "Вьетнамский донг",
  "BTC": "Биткоин",
  "XAG": "Серебро (тройская унция)",
  "XAU": "Золото (тройская унция)"
};

final Map<String, dynamic> aliasesEN = {
  "RUB": "Russian Ruble",
  "USD": "United States Dollar",
  "EUR": "Euro",
  "BYN": "Belarusian Ruble",
  "KZT": "Kazakhstani Tenge",
  "AED": "United Arab Emirates Dirham",
  "AMD": "Armenian Dram",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "AZN": "Azerbaijani Manat",
  "BGN": "Bulgarian Lev",
  "BRL": "Brazilian Real",
  "CAD": "Canadian Dollar",
  "CHF": "Swiss Franc",
  "CLP": "Chilean Peso",
  "CNY": "Chinese Yuan",
  "CZK": "Czech Koruna",
  "DKK": "Danish Krone",
  "EGP": "Egyptian Pound",
  "GBP": "British Pound Sterling",
  "GEL": "Georgian Lari",
  "HKD": "Hong Kong Dollar",
  "HRK": "Croatian Kuna",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli Sheqel",
  "INR": "Indian Rupee",
  "IRR": "Iranian Rial",
  "ISK": "Icelandic Krona",
  "JPY": "Japanese Yen",
  "KGS": "Kyrgystani Som",
  "KRW": "South Korean Won",
  "LTL": "Lithuanian Litas",
  "LVL": "Latvian Lats",
  "MDL": "Moldovan Leu",
  "MNT": "Mongolian Tugrik",
  "MVR": "Maldivian Rufiyaa",
  "MXN": "Mexican Peso",
  "NOK": "Norwegian Krone",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "PHP": "Philippine Peso",
  "PLN": "Polish Zloty",
  "RON": "Romanian Leu",
  "RSD": "Serbian Dinar",
  "SCR": "Seychellois Rupee",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "THB": "Thai Baht",
  "TJS": "Tajikistani Somoni",
  "TMT": "Turkmenistani Manat",
  "TRY": "Turkish Lira",
  "TWD": "Taiwan Dollar",
  "UAH": "Ukrainian Hryvnia",
  "UZS": "Uzbekistan Som",
  "VND": "Vietnamese Dong",
  "BTC": "Bitcoin",
  "XAG": "Silver (troy ounce)",
  "XAU": "Gold (troy ounce)"
};

final List<String> currenciesOrder = [
  "RUB",
  "USD",
  "EUR",
  "BYN",
  "KZT",
  "AMD",
  "ARS",
  "AUD",
  "AZN",
  "BGN",
  "BRL",
  "CAD",
  "CHF",
  "CLP",
  "CNY",
  "CZK",
  "DKK",
  "AED",
  "EGP",
  "GBP",
  "GEL",
  "HKD",
  "HRK",
  "IDR",
  "ILS",
  "INR",
  "IRR",
  "ISK",
  "JPY",
  "KGS",
  "KRW",
  "LTL",
  "LVL",
  "MDL",
  "MNT",
  "MVR",
  "MXN",
  "NOK",
  "NPR",
  "NZD",
  "PHP",
  "PLN",
  "RON",
  "RSD",
  "SCR",
  "SEK",
  "SGD",
  "THB",
  "TJS",
  "TMT",
  "TRY",
  "TWD",
  "UAH",
  "UZS",
  "VND",
  "BTC",
  "XAG",
  "XAU"
];
